apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: ansible-tower-console-link
spec:
  applicationMenu:
    imageURL: https://upload.wikimedia.org/wikipedia/commons/2/24/Ansible_logo.svg
    section: Red Hat Applications
  href: https://ansible-tower-web-svc-tower.apps.SPECIFY_YOUR_CLUSTER_NAME.SPECIFY_YOUR_CLUSTER_DOMAIN/
  location: ApplicationMenu
  text: Red Hat Ansible Tower