
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: pacman-dev-clusters
  namespace: pacman-app-dev
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    clusterReplicas: 2
    matchExpressions:
    - key: region
      operator: In
      values:
      - ap-southeast-1
      - ap-southeast-2
      - ap-northeast-1
      - southeastasia
    matchLabels:
      environment: dev
      apps/pacman: deployed
