apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base

resources:
  - pacman-scc.yaml

patchesStrategicMerge:
- pacman-deployment.yaml
- pacman-secret.yaml
- pacman-tm-route.yaml
