
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/github-path: deploy
  name: pacman-app-prod
  namespace: pacman-app-prod
  labels:
    app.kubernetes.io/name: pacman-prod
spec:
  channel: pacman-app-prod/pacman-app-prod-latest
#  hooksecretref:
#    name: toweraccess
  placement:
    placementRef:
      kind: PlacementRule
      name: pacman-prod-clusters