
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: etherpad-dev-deployment
spec:
  workspaces:
    - name: source  
  steps:
    - name: etherpad-dev-deployment
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source  
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo "**** DEV ENVIRONMENT: Creating application on RH ACM ****"
          oc apply -f multipleclusters-multiple-envs/rhacm/dev/application.yaml

          echo "**** DEV ENVIRONMENT: Creating channel on RH ACM ****"
          oc apply -f multipleclusters-multiple-envs/rhacm/dev/channel.yaml

          echo "**** DEV ENVIRONMENT: Creating placementrule on RH ACM ****"
          oc apply -f multipleclusters-multiple-envs/rhacm/dev/placement-rule.yaml

          echo "**** DEV ENVIRONMENT: Creating subscription on RH ACM ****"
          oc apply -f multipleclusters-multiple-envs/rhacm/dev/subscription.yaml