apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: acm-sync
spec:
  inputs:
    resources:
      - name: image
        type: image
    params:
      - name: APP_NAME
        description: The name of the application
        default: 'pacman-app-tekton'
        type: string
      - name: APP_VERSION
        description: The version of the application
        default: '1.0'
        type: string
      - name: DEPLOY_PROJECT
        description: The project where you deploy the app
        default: 'pacman-app-dev'
        type: string
      - name: PROMOTE_PROJECT
        description: The project where you promote the app
        default: 'pacman-app-qa'
        type: string

  outputs:
    resources:
      - name: image
        type: image

  steps:
      - name: acm-sync-dev
        image: quay.io/eformat/openshift-kustomize:latest
        workingDir: /workspace/source
        command: ["/bin/bash", "-c"]
        args:
          - |-
            echo "$APP_VERSION"
            kustomize build deploy/overlays/dev | envsubst > deploy/kustomize-output/dev/dev.yaml
            git remote remove origin
            git remote add origin https://xxxx@github.com/waynedovey/k8s-pacman-app.git
            git add deploy/kustomize-output/dev/dev.yaml
            git commit -m "bump version $APP_VERSION"
            git push