
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: pacman-app-qa
  namespace: pacman-app-qa
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: In
      values:
      - pacman