---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: pacman-app-latest
  namespace: pacman-app-qa
  labels:
    app.kubernetes.io/name: pacman-qa
  annotations:
    apps.open-cluster-management.io/github-path: deploy/kustomize-output/qa
spec:
  type: GitHub
  pathname: https://github.com/waynedovey/k8s-pacman-app.git
  # secretRef:
  #   name: github-credentials