
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/github-path: deploy/kustomize-output/qa
  name: pacman-app-qa
  namespace: pacman-app-qa
  labels:
    app.kubernetes.io/name: pacman-qa
spec:
  channel: pacman-app-qa/pacman-app-qa-latest
#  hooksecretref:
#    name: toweraccess
  placement:
    placementRef:
      kind: PlacementRule
      name: pacman-qa-clusters