apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: pacman
    app.kubernetes.io/name: pacman
  name: pacman
  namespace: pacman-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pacman
      app.kubernetes.io/name: pacman
  template:
    metadata:
      labels:
        name: pacman
        app.kubernetes.io/name: pacman
    spec:
      containers:
      - image: quay.io/jpacker/nodejs-pacman-app:green
        name: pacman
        ports:
        - containerPort: 8080
          name: http-server
        env:
        - name: MONGO_SERVICE_HOST
          value: mongodb.pacman-app.svc.clusterset.local
        - name: MONGO_AUTH_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: mongodb-users-secret
        - name: MONGO_AUTH_PWD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: mongodb-users-secret
        - name: MONGO_DATABASE
          value: pacman
        - name: MY_MONGO_PORT
          value: "27017"
        - name: MONGO_USE_SSL
          value: "false"
        - name: MONGO_VALIDATE_SSL
          value: "false"
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName

