apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-ansible-tower-prep
  namespace: tower-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-ansible-tower-prep-project
        spec:
          remediationAction: enforce # will be overridden by remediationAction in parent policy
          severity: high
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["*"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: project.openshift.io/v1
                kind: Project
                metadata:
                  name: tower
                spec: {}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-ansible-tower-prep
        spec:
          remediationAction: enforce # will be overridden by remediationAction in parent policy
          severity: high
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["*"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: PersistentVolumeClaim
                apiVersion: v1
                metadata:
                  name: postgresql
                  namespace: tower
                spec:
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 5Gi
                #  storageClassName: gp2
                  volumeMode: Filesystem
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-ansible-tower-prep
  namespace: tower-policies
placementRef:
  name: placement-policy-ansible-tower-prep
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-ansible-tower-prep
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-ansible-tower-prep
  namespace: tower-policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      []  # selects all clusters if not specified
    matchLabels:
      name: local-cluster
