kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
  name: pacman
  namespace: pacman-app-qa
  labels:
    app.kubernetes.io/name: pacman
    app.kubernetes.io/part-of: pacman-app
    name: pacman
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pacman
      name: pacman
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: pacman
        name: pacman
    spec:
      restartPolicy: Always
      serviceAccountName: pacman-app-qa
      schedulerName: default-scheduler
      hostNetwork: true
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
              scheme: HTTP
              httpHeaders:
                - name: X-Powered-By
                  value: Express
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
              scheme: HTTP
              httpHeaders:
                - name: X-Powered-By
                  value: Express
            initialDelaySeconds: 3
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /healthcheck
              port: 8080
              scheme: HTTP
              httpHeaders:
                - name: X-Powered-By
                  value: Express
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3                        
          terminationMessagePath: /dev/termination-log
          name: pacman
          env:
            - name: MONGO_SERVICE_HOST
              value: mongo1.pacman-app.svc.clusterset.local,mongo2.pacman-app.svc.clusterset.local,mongo3.pacman-app.svc.clusterset.local
            - name: MONGO_AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-users-secret
                  key: database-user
            - name: MONGO_AUTH_PWD
              valueFrom:
                secretKeyRef:
                  name: mongodb-users-secret
                  key: database-password
            - name: MONGO_DATABASE
              value: pacman-qa
            - name: MONGO_REPLICA_SET
              value: rs0
            - name: MY_MONGO_PORT
              value: '27017'
            - name: MONGO_USE_SSL
              value: 'false'
            - name: MONGO_VALIDATE_SSL
              value: 'false'
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          ports:
            - name: http-server
              hostPort: 8080
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: 'quay.io/wdovey/pacman-app:3.0'
      serviceAccount: pacman-app-qa
      dnsPolicy: ClusterFirstWithHostNet
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status: {}
